theme: jekyll-theme-minimal
title: Beginning Maker Tech
logo: jlaurentpdx.github.io/beginning-maker-tech/img/20190113_155017thumbnail300_225.jpg
description: A PCC Winter 2019 course for students of the Opening Doors Project.  
    
